api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Model/Api']
    patch_formats:
        json: ['application/merge-patch+json']
        versions: [3]
    swagger:
        api_keys:
            Bearer:
                name: Authorization
                type: header
