# See https://github.com/excelwebzone/EWZRecaptchaBundle for full configuration
ewz_recaptcha:
    public_key:  '%env(EWZ_RECAPTCHA_SITE_KEY)%'
    private_key: '%env(EWZ_RECAPTCHA_SECRET)%'
    locale_key:  "%locale%"
    locale_from_request: true
    ajax: false
    enabled: false
    api_host: www.google.com
    verify_host: false
