framework:
    secret: '%env(APP_SECRET)%'
    translator:      { fallbacks: ["%locale%"] }
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        name: remesas-api-local
        # handler_id set to null will use default session handler from php.ini
        #handler_id:  ~
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/../var/sessions"
#        handler_id: null
        # 1 Days lifetime (86400 seconds)
        cookie_lifetime: 86400
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    templating:
        engines: ['twig']

    default_locale:  "%locale%"

    fragments:       ~
    http_method_override: true