liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: '%kernel.project_dir%/%web_dir%'
        cache_prefix: media/cache
  loaders:
    default:
      filesystem:
        data_root: '%kernel.project_dir%/%web_dir%'

  filter_sets:
    cache: ~

    user_avatar:
      quality: 100
      filters:
        thumbnail: { size: [25,25], mode: inbound }
