<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TnConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TnConfigurationRepository extends EntityRepository
{
    public function getHas($option)
    {

        $data = $this->findOneBy(array('attr' => $option));

        if (!$data) {
            return false;
        }

        return true;

    }

    public function getOption($option, $default = NULL)
    {

        $data = $this->findOneBy(array('attr' => $option));

        if (!$data) {
            return $default;
        }

        return $data->getValue();

    }

    public function getConditions($value)
    {
        $query = $this->createQueryBuilder('cf')
            ->select('cf')
            ->where('cf.attr LIKE :book')
            ->setParameter('book', $value . "%");

        return $query->getQuery()->getResult();
    }
}
